### ISSUE TITLE
BadAuthentication using an App Password

### ISSUE THREAD

**Issue by NelsonGaldeman** [ShaunLWM/node-whatsapp-drive-extractor#2]
Hi! I'm trying to test the script but I'm getting BadAuthentication

    $ node --version
    v8.17.0
    $ waex -e username@gmail.com -p {APP_PASSWORD} -n {NUMBER} -i {DEVID} --list
    Error: [!] getGoogleAccountTokenFromAuth status: Error=BadAuthentication
        at Extractor.getGoogleAccountTokenFromAuth (/usr/local/lib/node_modules/node-whatsapp-drive-extractor/index.js:53:23)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:189:7)

I've read on the troubleshooting that there has been some issues on authentication using newer versions of Node, but I'm using version 8 as specified and getting the same error. I've double checked the app password is ok, generated a second one just in case but same result. Not sure if it's a bug or a config issue.

**Comment by ShaunLWM** [comment]
I just tested this library few days back. It used to work with Node v8 but it stopped working. Not only for this project, but many others as well

https://github.com/dweinstein/node-google-play/issues/123
https://github.com/matlink/gplaycli/issues/260

Still waiting for someone to find a fix for it :/

**Comment by sepo83** [comment]
Downgrading urllib3 fixed it for me with gplaycli (see https://github.com/matlink/gplaycli/issues/260#issuecomment-778663387)

**Comment by keldrox** [comment]
Hi, any solution for node-whatsapp-drive-extractor?

Thank you

**Comment by NelsonGaldeman** [comment]
> Hi, any solution for node-whatsapp-drive-extractor?
> 
> Thank you

Read the comment above yours

**Comment by ShaunLWM** [comment]
> Hi, any solution for node-whatsapp-drive-extractor?
> 
> Thank you

Apologise for not getting back to you. I haven't had the time to take a look into this. Seems like the python community has found the problem but not for node. Will keep this issue open till I have the time to take a deeper look into it or when the other issues are fixed in other repository. Example: https://github.com/dweinstein/node-google-play/issues/123

**Comment by dangerb3** [comment]
@ShaunLWM Hello, any updates?
